apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgmicroservice-ingress
  namespace: rizky18          # change if your namespace is different
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: rizky18.57.158.184.247.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgmicroservice-svc
                port:
                  number: 80
